#pragma once
// Debug
#define DEBUG
#define SHOW_CONSOLE
#define SET_TITLE_AS_FPS

// Windows
#define WIN_CLASS_NAME L"GameUIT"
#define WIN_TITLE L"GameUIT"
#define SCREEN_WIDTH 600
#define SCREEN_HEIGHT 525
#define BUFFER_WIDTH 256
#define BUFFER_HEIGHT 224

// KEY
#define GAME_KEY_LEFT VK_LEFT
#define GAME_KEY_RIGHT VK_RIGHT
#define GAME_KEY_UP VK_UP
#define GAME_KEY_DOWN VK_DOWN
#define GAME_KEY_JUMP 88
#define GAME_KEY_ATTACK 90

// VELOCITY
#define MOVEMENT_UPDATE_TIME 0.01666666666f
#define PLAYER_VELOCITY_X_MAX 100
#define PLAYER_ACC_X 5